export default {
  preset: 'ts-jest',
  testEnvironment: 'node',
  setupFiles: ['<rootDir>/jest.setup.ts'],
  moduleNameMapper: {
    '^src/(.*)$': '<rootDir>/src/$1',
    '^generated/prisma$': '<rootDir>/generated/prisma',
  },
  moduleFileExtensions: ['ts', 'js', 'json'],
  rootDir: '.',
  //testRegex: '.*\\.spec\\.ts$',
  collectCoverageFrom: [
    'src/**/customer.service.ts',
    'src/**/auth.service.ts',
    'src/**/cloudinary.service.ts',
    'src/**/promotional-discount.service.ts',
    //'src/**/order-header.service.ts',
    //'src/**/order-item.service.ts',
    'src/**/user.service.ts',
    'src/**/feature.service.ts',
    'src/**/option-value.service.ts',
    'src/**/option.service.ts',
    'src/**/product.service.ts',
    'src/**/product-file.service.ts',
    'src/**/product-variation.service.ts',
    'src/**/shop-cart.service.ts',
    'src/**/stripe.service.ts',
  ],
  testMatch: [
    '**/src/**/customer.service.spec.ts',
    '**/src/**/auth.service.spec.ts',
    '**/src/**/cloudinary.service.spec.ts',
    '**/src/**/promotional-discount.service.spec.ts',
    //'**/src/**/order-header.service.spec.ts',
    //'**/src/**/order-item.service.spec.ts',
    '**/src/**/user.service.spec.ts',
    '**/src/**/feature.service.spec.ts',
    '**/src/**/option-value.service.spec.ts',
    '**/src/**/option.service.spec.ts',
    '**/src/**/product.service.spec.ts',
    '**/src/**/product-file.service.spec.ts',
    '**/src/**/product-variation.service.spec.ts',
    '**/src/**/shop-cart.service.spec.ts',
    '**/src/**/stripe.service.spec.ts',
  ],
  transform: {
    '^.+\\.ts$': 'ts-jest',
  },
};
